#!/bin/bash

## old script that would lock all computers at my desk at once
purple-remote "setstatus?status=away&message=Not At My Desk"
/usr/bin/gnome-screensaver-command --lock && purple-remote "setstatus?status=available&message="

#ssh appleComputer 'open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app'
#ssh windowsVM 'rundll32.exe user32.dll, LockWorkStation'
#while [ `/usr/bin/gnome-screensaver-command --lock` ]
#/usr/bin/gnome-screensaver-command --lock
#until [ `/usr/bin/gnome-screensaver-command --lock` ]; do
#   if [[ $changed -ne "1" ]]; then
#	changed=1
#   fi
#done

